# Generated by Django 4.2.3 on 2023-07-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/banner', verbose_name='Banner uchun rasm')),
            ],
            options={
                'verbose_name': 'Banner rasmi',
                'verbose_name_plural': '1. Banner rasmlari',
            },
        ),
        migrations.CreateModel(
            name='Consert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Konsert nomi yoki artist ismi')),
                ('image', models.ImageField(upload_to='images/consert', verbose_name='Konsert uchun rasm yuklang')),
                ('date', models.DateField()),
                ('langugae', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=10, verbose_name="Ma'lumot chiqariladigan til")),
            ],
            options={
                'verbose_name': 'Konsert',
                'verbose_name_plural': '2. Konsertlar',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tadbir nomi')),
                ('image', models.ImageField(upload_to='images/event', verbose_name='Tadbir uchun rasm yuklang')),
                ('date', models.DateField()),
                ('langugae', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=10, verbose_name="Ma'lumot chiqariladigan til")),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': '3. Tadbirlar',
            },
        ),
    ]
