# Generated by Django 4.2.3 on 2023-07-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_langugae_consert_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Tadbir haqida qisqacha ma'lumot"),
        ),
    ]
