# Generated by Django 4.2.3 on 2023-07-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name': 'Banner rasmi ', 'verbose_name_plural': '1. Banner rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='consert',
            options={'verbose_name': 'Konsert ', 'verbose_name_plural': '2. Konsertlar'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Tadbir ', 'verbose_name_plural': '3. Tadbirlar'},
        ),
    ]
